// Built-in list of popular websites used to generate decoy browsing traffic.
// Loaded by the popup ("Load popular sites") so the user can drop a broad,
// varied set into their list and then trim/add as they like.
//
// The mix spans search, news, shopping, reference, tech, media, finance,
// travel, and more — the goal is breadth so the noise looks like ordinary,
// wide-ranging browsing rather than a narrow pattern.

const POPULAR_SITES = [
  // Search & portals
  "https://www.google.com",
  "https://www.bing.com",
  "https://duckduckgo.com",
  "https://www.yahoo.com",
  "https://www.ecosia.org",
  "https://www.startpage.com",
  // Reference & knowledge
  "https://www.wikipedia.org",
  "https://www.britannica.com",
  "https://www.wikihow.com",
  "https://www.quora.com",
  "https://stackoverflow.com",
  "https://www.merriam-webster.com",
  "https://dictionary.cambridge.org",
  "https://www.wolframalpha.com",
  // News & magazines
  "https://www.bbc.com",
  "https://www.cnn.com",
  "https://www.nytimes.com",
  "https://www.theguardian.com",
  "https://www.reuters.com",
  "https://apnews.com",
  "https://www.npr.org",
  "https://www.washingtonpost.com",
  "https://www.forbes.com",
  "https://www.bloomberg.com",
  "https://www.wsj.com",
  "https://www.economist.com",
  "https://www.time.com",
  "https://www.nationalgeographic.com",
  "https://www.aljazeera.com",
  "https://www.usatoday.com",
  // Tech & science
  "https://www.theverge.com",
  "https://techcrunch.com",
  "https://arstechnica.com",
  "https://www.wired.com",
  "https://www.engadget.com",
  "https://www.cnet.com",
  "https://www.zdnet.com",
  "https://www.tomshardware.com",
  "https://www.digitaltrends.com",
  "https://www.nature.com",
  "https://www.scientificamerican.com",
  "https://www.sciencedaily.com",
  "https://github.com",
  "https://gitlab.com",
  "https://dev.to",
  "https://hackernoon.com",
  "https://news.ycombinator.com",
  // Shopping & commerce
  "https://www.amazon.com",
  "https://www.ebay.com",
  "https://www.walmart.com",
  "https://www.etsy.com",
  "https://www.target.com",
  "https://www.bestbuy.com",
  "https://www.aliexpress.com",
  "https://www.ikea.com",
  "https://www.homedepot.com",
  "https://www.costco.com",
  "https://www.newegg.com",
  "https://www.wayfair.com",
  // Social & community
  "https://www.reddit.com",
  "https://www.pinterest.com",
  "https://medium.com",
  "https://www.tumblr.com",
  "https://mastodon.social",
  // Media, video & music
  "https://www.youtube.com",
  "https://vimeo.com",
  "https://www.twitch.tv",
  "https://www.dailymotion.com",
  "https://www.imdb.com",
  "https://www.rottentomatoes.com",
  "https://www.spotify.com",
  "https://soundcloud.com",
  "https://www.last.fm",
  "https://www.goodreads.com",
  // Reference / how-to / lifestyle
  "https://www.allrecipes.com",
  "https://www.foodnetwork.com",
  "https://www.epicurious.com",
  "https://www.healthline.com",
  "https://www.webmd.com",
  "https://www.mayoclinic.org",
  "https://www.verywellhealth.com",
  "https://www.self.com",
  "https://www.menshealth.com",
  // Travel & maps
  "https://www.tripadvisor.com",
  "https://www.booking.com",
  "https://www.expedia.com",
  "https://www.airbnb.com",
  "https://www.lonelyplanet.com",
  "https://www.kayak.com",
  "https://www.skyscanner.net",
  "https://www.google.com/maps",
  // Finance & business
  "https://www.investopedia.com",
  "https://finance.yahoo.com",
  "https://www.marketwatch.com",
  "https://www.cnbc.com",
  "https://www.nerdwallet.com",
  "https://www.morningstar.com",
  // Sports
  "https://www.espn.com",
  "https://www.bleacherreport.com",
  "https://www.skysports.com",
  "https://www.nba.com",
  "https://www.nfl.com",
  "https://www.formula1.com",
  // Education & learning
  "https://www.coursera.org",
  "https://www.khanacademy.org",
  "https://www.edx.org",
  "https://www.udemy.com",
  "https://www.ted.com",
  "https://www.duolingo.com",
  // Weather & utilities
  "https://weather.com",
  "https://www.accuweather.com",
  "https://www.wunderground.com",
  // Entertainment & misc
  "https://www.buzzfeed.com",
  "https://www.mentalfloss.com",
  "https://www.atlasobscura.com",
  "https://xkcd.com",
  "https://www.smithsonianmag.com",
  "https://www.history.com",
  "https://www.space.com",
  "https://www.livescience.com"
];

// Expose in both service-worker and window contexts.
if (typeof self !== "undefined") self.POPULAR_SITES = POPULAR_SITES;
